version: "3.8"

services:
  db:
    build: ./Database
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: demodb
    restart: always

  server:
    image: demo-server
    build: .
    environment:
      - PORT=3001
      - DBHOST=db
      - DBPORT=3306
      - DBUSER=root
      - DBNAME=demodb
      - DBPASSWORD=pass
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
