version: "3.8"

services:
  db:
    build: ./Database
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: demodb
    #for data persistent
    volumes:
      - ./mysql-data-dump:/var/lib/mysql
    restart: always

  server:
    #build your image locally or push the image to dockerhub abd use image name accordingly
    image: sagar4321/demo-server
    environment:
      - PORT=3001
      - DBHOST=db
      - DBPORT=3306
      - DBUSER=root
      - DBNAME=demodb
      - DBPASSWORD=pass
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db

  web:
    #build your image locally or push the image to dockerhub abd use image name accordingly
    image: sagar4321/demo-web
    environment:
      - SERVER_URL=http://0.0.0.0:3001
    ports:
      - 8080:8080
    depends_on:
      - server

  # mysql client
  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
